# Generated by Django 4.1.7 on 2023-03-25 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_images_post_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post_Images',
            new_name='PostImages',
        ),
    ]
