# Generated by Django 4.1.7 on 2023-03-28 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_post_header_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimages',
            options={'verbose_name_plural': 'Post Images'},
        ),
    ]
